espaces = ' ' * 25
print(f'{espaces} 12 rue du Homevent')
print(f'{espaces} Landes Scintillantes')
print()
print()
print('Cher Monsieur,')
print()
print('Permettez-moi de vous signaler que des tuiles manquent')
print('sur le toit des toilettes du jardin.')
print('Le vent de la nuit dernière les a faites s\'envoler.')
print()
print('Salutations')
print('Michel Line')