espaces = ' ' * 25
print(f'{espaces} 30 la Saudrais')
print(f'{espaces} Bréal-sous-Montfort')
print()
print()
print('Ma très chère maman,')
print()
print('Je me permet de te contacter pour te prévenir que tu me manque énormément !')
print()
print('Je te fais d\'énormes bisous')
print('Ewen')